### ISSUE TITLE
loading screen hangs indefinitely after hitting Write SD Card 

### ISSUE THREAD

**Issue by laneschmidt** [MatthewCallis/super-pads#103]
bug/possible feature request -- macOS big sur 11.2.3

first of all, really like the application, thank you! makes the standard Roland version look like windows 95

loading screen hangs indefinitely when i try to write more than a few files to an SD card. they're all valid wav files so i'm not sure what's going on. i let the process run for 25 minutes and assumed it errored out at that point. have to run `killall 'Super Pads'` to get it to stop.

i understand that writing to SD cards can take awhile and it's hard to tell if the process is hanging/erroring out or just taking a long time, so it would be cool to have a progress bar. it's something i could look at implementing. 

first off, is there a log file i can view somewhere?

**Comment by MatthewCallis** [comment]
I will add a logging window in this next release with the sound preview and waveform display that I have going.

I’m curious, what file types and sizes were you adding? It should never take 25 minutes unless it was a really obtuse format.

**Comment by laneschmidt** [comment]
ok. like i said they're all wav files, biggest one was around 15 MB. maybe my card write speed is abnormally slow or something. i just added a bank of one-shots and it's been loading for about 5 minutes and counting so i'm starting to think it didn't error out, it just took a very long time.

**Comment by MatthewCallis** [comment]
What tends to happen is there are certain WAV files that end up hanging due to weird chunk issues, I think the latest version of https://github.com/uttori/uttori-audio-wave should resolve this particular issue, but a log would still be very useful.
