### ISSUE TITLE
Samples are overwritten

### ISSUE THREAD

**Issue by damsmcfly** [MatthewCallis/super-pads#108]
Hi,
I found an issue, not sure if you can reproduce it on your end:

- Let's say i load samples on my SD card with Super Pads.
- Then i put the SD card in my SP 404 A (yeah, not an SX), and create new samples from the machine.
- If i put the SD back in the computer and launch Super Pads, Super Pads will not recognize the samples created on the SP.

It looks like i need to delete "super-pads.json" before every time i launch the app, otherwise all the samples created on the SP will be overwritten by Super Pads.
Now that i know the trick it's not a big deal, but i'm not sure this is supposed to work like that. Anyway, i really enjoy this app, it's wonderful, thanks a lot for this !

**Comment by laneschmidt** [comment]
+1, i just created an issue that is similar. it seems to get stuck on previous SD card states that it caches.

**Comment by MatthewCallis** [comment]
I just released https://github.com/MatthewCallis/super-pads/releases/tag/1.2.1 which should fix this issue. The solution was to not store the data for now, in the next version I will add the ability to check files for changes.
