### ISSUE TITLE
samples being erased, moved, cut off, etc

### ISSUE THREAD

**Issue by laneschmidt** [MatthewCallis/super-pads#121]
super pads is wreaking havoc on my SD cards. i've been relying on it to organize live sets and have been going crazy trying to figure out why my songs are disappearing, being moved to random pads, or being cut off mid-song (the audio file gets cut somehow), but then i realized it was super pads! wish i could provide more information but the problems are very random and hard to pin down. many songs were lost forever :( i should have made backups

**Comment by laneschmidt** [comment]
i did a little testing today with 4 verified bounces that are 3-5 minutes long on a freshly formatted SD card. instead of using Super Pads, i just dumped them into the `SMPL` directory. one thing to note here is that Super Pads seems to think the card is still full (??), as if the previous SD card's state is cached and it cannot recognize the new state.

when i eject the card and move some stuff around manually in the 404, then plug it back into Super Pads, the new file locations aren't reflected. at this point i try and move the files around using Super Pads, then eject the card and plug it back into my 404. the samples are now at different pad locations (different than their original location AND different than the location selected in Super Pads - basically random locations), and one of them is missing altogether. and one of the samples is cut off at around 10 seconds.

finally, i go back into Super Pads and i see paths to files that don't exist. they may be left over from the first SD card file setup, i'm not sure. hope this helps.

**Comment by MatthewCallis** [comment]
I'm really sorry you had so many issues! I just released https://github.com/MatthewCallis/super-pads/releases/tag/1.2.1 which should fix this issue. The solution was to not store the data for now, in the next version I will add the ability to check files for changes.
